### ISSUE TITLE
Inconsistent power use at high timewarp with Near Future Electrical reactors

### ISSUE THREAD

**Issue by utilbird** [ChrisAdderley/DynamicBatteryStorage#104]
Noticed my cryogenic tanks were boiling off despite a significant power surplus at time warps above 100x, the DBS overlay indicates that the NFE reactors were underperforming at high timewarps. Unsure if their forced hibernation is an issue DBS can solve or something that needs to be brought up on NFE specifically.

All timewarps <=100x
![image](https://github.com/user-attachments/assets/8846e0f0-1b84-4257-b977-860c3d396cdd)

All timewarps >100x
![image](https://github.com/user-attachments/assets/7fa51015-bcdd-4cbe-ab3b-0c2e585063dc)

**Comment by utilbird** [comment]
might be worth noting that it doesn't seem to affect the ship electricy resource (batteries are still full - at least visually), rather it shuts down some electricty consuming parts, most notably cryotanks.

**Comment by ChrisAdderley** [comment]
I can't reproduce this.

Basic test case:
1x
![image](https://github.com/user-attachments/assets/5ad7ceb4-9a08-4f4f-a971-cc778973dea2)

1000000x
![image](https://github.com/user-attachments/assets/29a3bffb-bc28-4bdd-866a-b7d979825fcb)

Logs, modlist, images of vessel, ideally a small reproducible case.

**Comment by ChrisAdderley** [comment]
Hmm ok, so I reproduced it with a more complex vessel. It's to do with >1 reactor and the automatic reactor throttling. It may take a while to fix. 
You can work around it by setting the reactors to Manual mode in the PAW and dragging the slider to where they need to be. 

And yes - it does affect the vessel, not just the display.

**Comment by ChrisAdderley** [comment]
A fix exists with the newest DBS release but requires the newest SH release (0.8.1) as well.
