### ISSUE TITLE
Wrong target framework version

### ISSUE THREAD

**Issue by HebaruSan** [ChrisAdderley/DynamicBatteryStorage#17]
KSP mods should have `v3.5` here:

https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/b840e9939367bbdb7d6238bbdc2eef844420b95d/Source/DynamicBatteryStorage/DynamicBatteryStorage.csproj#L13

Originally reported by forum user Tonka Crash at:

https://forum.kerbalspaceprogram.com/index.php?/topic/183869-mods-with-wrong-net-target-framework/

**Comment by ChrisAdderley** [comment]
Fixed in #18
