### ISSUE TITLE
Dynamic Battery Storage doesnt recognize electricity use by other mods

### ISSUE THREAD

**Issue by GladiatorHK** [ChrisAdderley/DynamicBatteryStorage#20]
Would it be possible for this mod to work with TAC life support mod, because I have the issue of running out of electricity when time warping which results in my kerbals dying.  The mod works great with other means of power consumption though(TAC life support drains electric charge per kerbal just to keep them alive).  If it wouldn't be possible does anyone know of an alternate solution to this.

**Comment by ChrisAdderley** [comment]
It's... possible generally, but I had a look at the TAC code and it's not really transparent to the method I use to retrieve energy consumption. I think I'd need to basically replicate how TAC calculates power draw which is a messy way of doing things. 

I might suggest asking in the thread first. I see that `0.02125/s` is the rate of consumption per crew member, which does mean that the electrical draw is fairly low. That indicates that at 100000x time warp, you should need a maximum storage of ~50 EC/crew member for no problems to occur, which seems pretty reasonable to build into a ship.

**Comment by ChrisAdderley** [comment]
Added to #26.
