### ISSUE TITLE
Settings File Missing?

### ISSUE THREAD

**Issue by 7ranceaddic7** [ChrisAdderley/DynamicBatteryStorage#21]
Is there supposed to be a settings file available?  I keep getting this in the KSP.log:

[LOG 15:22:39.208] [Dynamic Battery Storage]: Settings: Started loading
[LOG 15:22:39.208] [Dynamic Battery Storage]: Settings: Couldn't find settings file, using defaults
[LOG 15:22:39.209] [Dynamic Battery Storage]: Settings: Finished loading

**Comment by ChrisAdderley** [comment]
A basic settings file has been included with 2.0.0
