### ISSUE TITLE
ReFactor feedback

### ISSUE THREAD

**Issue by zorg2044** [ChrisAdderley/DynamicBatteryStorage#22]
Hi Nertea, been testing the refactor  and I'll post any feedback or issues I have here.

1) In the VAB planner I found that if I check a part that is disabled by default such as an engine or transmitter, it becomes unchecked as soon as a change is made to the craft. It could be a bit tedious having to re-enable say a cluster of ion engines everytime you add a battery or change capacitor discharge rate or whatever.

2) If possible, I think adding support for life support EC consumption for the popular life support mods (TAC, USI, Snacks, Kerbalism) could be nice. Perhaps its not as easy as it sounds? With Amp Year and TAC, the module life support shows up in the amp year planner at least, but without a value.

3) Looks like capacitors have the opposite problem to no.1, they are always automatically checked when a change is made.

4) Capacitors appear under batteries in the consuption side of the UI. However it seems to contribute just fine as a power source in the calculations.

This UI is v v cool btw :) Far easier than amp year.

**Comment by ChrisAdderley** [comment]
Ok some fixes with the latest commits to the branch
1. After some work this is now resolved, in the VAB adding or removing parts should keep the settings
2. As discussed, probably not in the first release
3/4. Capacitors I put under 'batteries' category, I could change this to be a different name. capacitors are weird though, they can either be producers or consumers. This is something for the future - moving them between the panels dynamically is currently beyond the UI's powers.

**Comment by ChrisAdderley** [comment]
released... we'll see how it all goes.
