### ISSUE TITLE
Kerbalism 3 Support please

### ISSUE THREAD

**Issue by Coyote21** [ChrisAdderley/DynamicBatteryStorage#28]
Currently the mod is wildly inaccurate in calculating ec usage by data transmitters (reads 9.3 ec/s when it should be 0.02 ec/s) probably b/c kerbalism changes how science transmission works.

**Comment by ChrisAdderley** [comment]
Unfortunately Kerbalism changes almost everything about how electricity works, so I have this note in the forum thread:

> Q: What mods will you NOT support?
A: Kerbalism and KSPI have their own planners and brokers and don't need this mod.
