### ISSUE TITLE
Support for RealBattery

### ISSUE THREAD

**Issue by blackliner** [ChrisAdderley/DynamicBatteryStorage#3]
Hi Chris,

I'd like to add support for my RealBattery mod. IMHO there are 2 things to do:

- Overthink your algorithm at [RefreshVesselElectricalData](https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/DynamicBatteryStorage.cs#L197;) Don't assume if its a producer it can't be a consumer as well. Why? My batteries are dynamically switching from being a consumer (thats when the battery is charging up) to being a producer (discharging the battery gives EC to the resource pool)
- extend [PowerConsumer](https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/PowerConsumer.cs) and [PowerProducer](https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/master/Source/DynamicBatteryStorage/PowerProducer.cs) 

**PR** [#4](https://github.com/ChrisAdderley/DynamicBatteryStorage/pull/4)

**Comment by ChrisAdderley** [comment]
Important to note that there's no such thing as a dynamic module in stock or anything I support at the moment.... so this is the first instance of that. 

Let's leave this ticket open until we are sure the integration is complete.

**Comment by blackliner** [comment]
Not the module is dynamic, but it is both a producer AND consumer of EC. Without the second change, my stuff won't be able to be considered as a consumer.

**Comment by ChrisAdderley** [comment]
Dynamic in this context = can be producer or consumer.

**Comment by ChrisAdderley** [comment]
So just to verify this concept works for you... I've reduced the size of the interface somewhat. Handlers are now defined on a per-module basis rather than a large blob of consumers and a large blob of producers. Here's the one for RB:

https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/feature/dynamic/Source/DynamicBatteryStorage/Handlers/RealBatteryPowerHandlers.cs

The `GetPower()` method now just reports the power delta, so negative if consuming, positive if producing, and the rest.
It's now up to anyone writing support configs to just implement the methods in the template class for their own class. 

https://github.com/ChrisAdderley/DynamicBatteryStorage/blob/feature/dynamic/Source/DynamicBatteryStorage/Handlers/PowerHandler.cs

This will be in the next released version but will need a bunch of testing so that might be a while.

**Comment by blackliner** [comment]
Wow, nice job. I am currently in Spain for work, so I don't have access to my PC. But what I can see from my phone: I like :-)

Are your NFT handlers still WIP? Because I think your consumers will need to negate their power.

Again, thanks for the work, I am sorry I use DBS and now you have to maintain it :-) but I think it is a very important mod! The whole concept should also work for any massless resource, right? ;-)

**Comment by ChrisAdderley** [comment]
Yes... this hasn't even been built yet haha.

**Comment by ChrisAdderley** [comment]
I'll probably deploy this as a new release in the next week - I'd appreciate if you could test your the implementation before then :)

**Comment by blackliner** [comment]
I'll try to get some PC time today or tomorrow.

Need to look at the sign for power again, somehow your debug window shows a negative value if a RealBattery is producing EC.

**Comment by blackliner** [comment]
Need to look at the sign for power again, somehow your debug window shows a negative value if a RealBattery is producing EC.

**Comment by blackliner** [comment]
Hi Chris,
i am thinking of switching from PartModules to a VesselModule, since the way i am balancing the load between the batteries is already (sortof) centralized. How could we enable DBS to support that? Would it work without PartModules at all? Or what is your expirience, should i stick with PartModules for the batteries and do an additional loadBalancer_VesselModule?

Cheers Flo

**Comment by ChrisAdderley** [comment]
> Need to look at the sign for power again, somehow your debug window shows a negative value if a RealBattery is producing EC.

I merged your PR on this which flipped the sign, which is it?

> i am thinking of switching from PartModules to a VesselModule, since the way i am balancing the load between the batteries is already (sortof) centralized. How could we enable DBS to support that? Would it work without PartModules at all? Or what is your expirience, should i stick with PartModules for the batteries and do an additional loadBalancer_VesselModule?

Easiest way to do this is have your VesselModule balance the load and inform the batteries what they should produce, then DBS looks at that information

**Comment by blackliner** [comment]
Thank you, i am still at figuring out a good way to do this. I came to that idea because someone made a PR to support RealFuels. The PR made no sense, but then the idea came for "dumb" tanks and a smart VM.

For the issue with the sign, i am currently testing it, should have something in a few minutes... and here we go: https://i.imgur.com/hSRTvIE.jpg

- i am displaying the public double lastECpower; negative means discharging
- my -15 EC/s are reported as +15EC/s via GetPower by * -1 because DBS is assuming positive = producer (right?)
- do i miss public override bool IsProducer() in my powerhandler?

**Comment by blackliner** [comment]
https://i.imgur.com/Rm9zwAb.jpg

here RealBattery is "consuming" 3.6 EC/s, getPower does a -3.6 out of it, and you show it in the producers tab. So i think i need the isProducer() -> PR'ing right away -> https://github.com/ChrisAdderley/DynamicBatteryStorage/pull/7
