### ISSUE TITLE
NF System Manager - a consumption item is summed into the Total Power Generation

### ISSUE THREAD

**Issue by yalov** [ChrisAdderley/DynamicBatteryStorage#49]
Light is an item (0.06 EC/s) in the Power Comsumption, but it is summed into the Power Generation

![](https://i.imgur.com/GMSdMMh.jpg)

**Comment by ChrisAdderley** [comment]
Changed in 2.1.1

**Comment by yalov** [comment]
Any chance we get 2.1.1 for 1.7.3?
