### ISSUE TITLE
NF System Manager - Mean Solar Altitude & Body Orbital Height

### ISSUE THREAD

**Issue by yalov** [ChrisAdderley/DynamicBatteryStorage#50]
https://www.dropbox.com/s/q895hs6j3ipu23f/20191111-210709.809.mp4?dl=0

 * Mean Solar Altitude - are showed values 1000 times smaller? 
100% efficiency at 13Mm from the Sun
 * Body Orbital Height - from 1km right away to 1Mm, can't be set to 100km, 200km, 500km.

**Comment by ChrisAdderley** [comment]
Changed in 2.1.1

**Comment by yalov** [comment]
![](https://i.imgur.com/e0MaXRj.jpg) ![](https://i.imgur.com/k9IOxBR.jpg)
Mean Solar Altitude there are Gm, and aren't Mm.
