### ISSUE TITLE
KopernicusSolarPanel

### ISSUE THREAD

**Issue by Sigma88** [ChrisAdderley/DynamicBatteryStorage#57]
the module "KopernicusSolarPanel" is going to be overhauled completely in the next kopernicus release and it will no longer replace the stock SolarPanel modules

The module itself will also be renamed to "KopernicusSolarPanels" which will trigger some NRE for mods that refer to "KopernicusSolarPanel"

I am torn between keeping an empty "KopernicusSolarPanel" module to avoid breaking mods that might refer to it, but at the same time if the issues don't show up people will not know that they need to change their mods.

I noticed that this mod refers to "KopernicusSolarPanel" so if you need help with switching to the new ones just let me know

**Comment by ChrisAdderley** [comment]
I looked at the code a while back and it looked like the way the new module worked would actually allow me to remove the Kopernicus support. TBD when you release with your final build, but I'm aware of it and tracking it.

**Comment by Sigma88** [comment]
Yes that was the intention, to make it less disruptive

Glad you are already tracking it
