### ISSUE TITLE
Power Flow not visible with Kopernicus 1.9.1-1 (CKAN Release)

### ISSUE THREAD

**Issue by hemeac** [ChrisAdderley/DynamicBatteryStorage#67]
As Kopernicus changes the ModuleDeployableSolarPanel to KopernicusSolarPanels, that makes all solar panels hidden in the Systems Manager UI.  Within DynamicBatteryStorageSettings.cfg, you have a KopernicusSolarPanel in Handlercategory which doesn't catch the name of the current module, but adding module = KopernicusSolarPanels as well as the related partmodulehandler appears to fix the issue.

**Comment by ChrisAdderley** [comment]
Released with 2.1.9
