### ISSUE TITLE
UI Scale

### ISSUE THREAD

**Issue by eberkain** [ChrisAdderley/DynamicBatteryStorage#72]
Would you consider adding an option for scaling the window size?  I find the text to be right on the edge of what I can manage to read, a little bigger would be a huge help to me and others that have vision issues.

**Comment by ChrisAdderley** [comment]
Implemented in latest revision of UI, will be in next release. UI size is now tied to global UI size in KSP settings.

**Comment by ChrisAdderley** [comment]
Released
