### ISSUE TITLE
Surface Darkness Time

### ISSUE THREAD

**Issue by eberkain** [ChrisAdderley/DynamicBatteryStorage#73]
Could an enhancement be added to the planner to toggle between the current orbital options, to a landed at surface mode?  Then just have a flat calculation for how long the night time is on the selected body.

**Comment by ChrisAdderley** [comment]
I had thought I implemented a feature where setting altitude to zero resulted in a surface darkness calculation. I can see if this is malfunctioning.

**Comment by ChrisAdderley** [comment]
This appears to work fine.
