### ISSUE TITLE
The mod isn't actually disabling itself when Kerbalism is installed

### ISSUE THREAD

**Issue by siimav** [ChrisAdderley/DynamicBatteryStorage#88]
https://github.com/post-kerbin-mining-corporation/DynamicBatteryStorage/blob/402ab6ffdc6dd5fd1c1050b503cb44fc50a04008/Source/DynamicBatteryStorage/DynamicBatteryStorage.cs#L52-L56
`VesselModule.enabled` will get overwritten every `Update` with the value from `VesselModule.ShouldBeActive()`. So `FixedUpdate` will still run and cause issues.

Relates to #48 and #53

**Comment by ChrisAdderley** [comment]
Released
