### ISSUE TITLE
Add ClickThroughBlocker functionality to the UI

### ISSUE THREAD

**Issue by TEJaaskelainen** [ChrisAdderley/DynamicBatteryStorage#89]
Hi

I'm getting more and more frustrated with this mod letting clicks through the windows, causing my ships to lose parts or misplacing them. Sometimes it's just an annoyance, most times it causes me having to redo half of the ship.

Why not add ClickThroughBlocker functionality to it? From what I read it's not too complicated a procedure.

**Comment by ChrisAdderley** [comment]
Released
