### ISSUE TITLE
It seems that there is still compatibility issue with KOP's multi-star mode

### ISSUE THREAD

**Issue by Aebestach** [ChrisAdderley/DynamicBatteryStorage#91]
![image](https://github.com/user-attachments/assets/3189ca81-ba87-4851-ab65-ce060362c56d)
[KSP.log](https://github.com/user-attachments/files/16607339/KSP.log)
Hi Nertea, glad you updated your mod again.
I installed the latest version of System Monitor and it still has compatibility issues with KOP's multi-star mode.
In flight mode it looks like the picture. In VAB/SPH, the solar panels are identified as 0 EC/s.

I also have a feature request: Can you make [WDSP](https://github.com/Aebestach/WeatherDrivenSolarPanel) compatible with System Monitor? WDSP is similar to the new KOP, but I added a few more variables to control the attenuation caused by weather.

Thank you so much

**Comment by ChrisAdderley** [comment]
Can you pare down the reproduction steps at all? My 'mimimum' multistar system test is GEP and I don't seem to get any errors. 

RE: WDSP, having to support so many different solar panel implementations is not very great. At this point the permutations are going to get very large.

**Comment by Aebestach** [comment]
I was tested in Kcalbeloh, Kcalbeloh + KOP
Is it possible to refer to [Fusebox Continued](https://forum.kerbalspaceprogram.com/topic/157896-112x-fusebox-continued-electric-charge-tracker-and-build-helper/) and change it?

**Comment by Aebestach** [comment]
![image](https://github.com/user-attachments/assets/380ae120-61f0-4d09-84bc-65572ea0a6b4)
[KSP.log](https://github.com/user-attachments/files/16607863/KSP.log)
Here is a log with only kcalbeloh environment

**Comment by ChrisAdderley** [comment]
Can you let me know what version of Kopernicus you are using?

**Comment by ChrisAdderley** [comment]
Yeah l guess a week ago the Kop method for managing solar panels changed completely so I'll have to rewrite this.

**Comment by Aebestach** [comment]
> Can you let me know what version of Kopernicus you are using?

v211, I misunderstood the new KOP support in the update log as the rewritten KOP

**Comment by ChrisAdderley** [comment]
The support that was added was for multiple stars in the planner which was all fine until then. Will have to work on it.

**Comment by Aebestach** [comment]
WDSP is implemented in the same way as the new KOP. If you want to adapt, please adapt it together. Thank you very much

**Comment by ChrisAdderley** [comment]
Ok after talking to RTB about this, I can say the following things
1. If you want DBS to work, you should stay on Kopernicus versions lower than 209. 
2. If you absolutely must use a Kopernicus version >= 209, you can get the prototype work I just did in the` kop-209` branch which adds some kind of support for the new method. It's not very tested though. 

We'll get a pathway forward in a bit to see how best to proceed.

**Comment by Aebestach** [comment]
The new KOP changes are my rewrite based on kerbalism, so I am also looking for ways to see if I can be compatible with them.

**Comment by Aebestach** [comment]
![image](https://github.com/user-attachments/assets/6681193b-2afe-4f3d-8224-04dc30aa6211)
In the new KOP, the module name is this, which is obtained through the GetSolarPanelModule() method at https://github.com/Kopernicus/Kopernicus/blob/c0d9d09570a4df886afc012f456363263f0adad0/src/Kopernicus/Components/KopernicusSolarPanel.cs#L207
So is it possible to get the module name and then call the corresponding class?

**Comment by Aebestach** [comment]
![image](https://github.com/user-attachments/assets/d59fea6a-d332-4e41-808f-470537da411d)
I tested it in the kop-209 branch and found duplicate components.
No issues found in the editor

**Comment by Aebestach** [comment]
![image](https://github.com/user-attachments/assets/99e5bb34-5bc4-45f2-adf4-8a3f4e82ecdc)


> ![image](https://private-user-images.githubusercontent.com/64588584/357720556-6681193b-2afe-4f3d-8224-04dc30aa6211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzU4NDAsIm5iZiI6MTcyMzYzNTU0MCwicGF0aCI6Ii82NDU4ODU4NC8zNTc3MjA1NTYtNjY4MTE5M2ItMmFmZS00ZjNkLTgyMjQtMDRkYzMwYWE2MjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDExMzkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwM2FiNGU5MDVhOGZjMmM1Y2RjN2RmYTBlNjZkNmM4ZWZmNDM0NzU3Y2QyMDZkMTYyMDI5ZjkwYTkwMDA2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YvbIYWSAFXhrJvVd7eivGrtwExCWopTEZ3fMMH0Cuek) In the new KOP, the module name is this, which is obtained through the GetSolarPanelModule() method at https://github.com/Kopernicus/Kopernicus/blob/c0d9d09570a4df886afc012f456363263f0adad0/src/Kopernicus/Components/KopernicusSolarPanel.cs#L207 So is it possible to get the module name and then call the corresponding class?

As I said here, I can add a variable in KOP to facilitate DBS to obtain the module name and then call the corresponding module. Can this variable help you?

**Comment by ChrisAdderley** [comment]
![image](https://github.com/user-attachments/assets/999a3100-d21c-400d-98c4-45c0a6f5df38)
I don't see duplicates here?
> As I said here, I can add a variable in KOP to facilitate DBS to obtain the module name and then call the corresponding module. Can this variable help you?

Not really.

**Comment by Aebestach** [comment]
![screenshot4](https://github.com/user-attachments/assets/4f72b31b-165f-4430-80c7-af2bddc12a8b)
![screenshot5](https://github.com/user-attachments/assets/cdded2b4-2cb4-49a1-8c7a-5c765f0a4acc)
The panel of the `ModuleCurvedSolarPanel` module will have this duplicate item

**Comment by ChrisAdderley** [comment]
Ah yep, haven't fixed that one yet... but I guess this hack works so I'll move it over to dev.

**Comment by Aebestach** [comment]
![screenshot6](https://github.com/user-attachments/assets/76298a93-b976-46d4-b7b2-b4a91a97a1f8)
![screenshot7](https://github.com/user-attachments/assets/07c1028a-2a0f-4d4d-bf6c-2312ecc51246)

- The solar panel module of SSTU cannot be recognized in the editor, but it works fine in the flight interface. Although as far as I know, few people use SSTU now.

![screenshot8](https://github.com/user-attachments/assets/aa88101b-46ec-4447-ac16-38aa863fcc5b)

- By the way, I am reporting a mod that DBS does not recognize at present. It is [Universal Storage II Finalized](https://spacedock.info/mod/2960/Universal%20Storage%20II%20Finalized). US2 also has its own solar panel module, called `USSolarSwitch`

- When switching back to the editor from the flight interface, the DBS data display is abnormal. You can see this [video](https://drive.google.com/file/d/12tiY2-ctdOptkG2IHGPD2nfyQmHzwR-v/view?usp=drive_link)
