### ISSUE TITLE
DBS UI does not respect Kopernicus display name

### ISSUE THREAD

**Issue by JacobB094** [ChrisAdderley/DynamicBatteryStorage#97]
In a nutshell, in KSRSS, Earth will show up as "Kerbin", despite displaying as Earth in the map view. UI should use the display name, as opposed to the internal name, when Kopernicus is installed. System Heat has the same problem.

**Comment by ChrisAdderley** [comment]
Fixed in last release (assuming Kopernicus does things right on their side)
